= Atelier Jenkins Pipeline

== Workshop #3 - Déploiement

=== Global Shared Libraries

1. Dans GitHub, forkez le projet https://github.com/ToulouseJAM/workshop-global-lib avec votre organisation GitHub
2. Au niveau de la configuration global de votre Jenkins ajouter la librairie partagée https://github.com/${VOTRE_ORGANISATION}/workshop-global-lib.git
3. Loader de manière implicite cette libraire


=== Configuration SSH

On va maintenant ajouter la configuration SSH nécessaire pour la connexion aux environnements de staging/production

Une paire de clé SSH a été générée spécifiquement pour les déploiements.

1. Récupérer le contenu de la clé privée via l'URL http://jenkins-workshop.pailloncy.fr/id_rsa_workshop

2. Aller dans la page link:http://<JENKINS_IP>:8080/credentials/store/system/domain/_/[http://<JENKINS_IP>:8080/credentials/store/system/domain/_/] puis `Add Credentials`
3. Ajouter une entrée de type `SSH username with private key`

** ID : deploy_key
** description : deploy_key
** Username : root
** Private key : ${CONTENU_CLE_PRIVEE}

Vous allez pouvoir maintenant utiliser ce credentials dans votre pipeline.

=== Déploiement des binaires sur l'environnement de staging

1. Utiliser les méthodes `copyFileTo(username,host,localpath,remotepath)`, `sshExec(username,host,command)` et `stopApplicationGracefully(username,host)` de votre librairie partagée pour :
* stopper votre application sur l'environnement de staging en faisant appel à la step `stopApplicationGracefully`
* copier votre binaire sur l'environnement staging avec `copyFileTo` (pour la destination, mettre `/root/app.jar`)
* démarrer votre application avec `sshExec`

Pour démarrer l'application, il faut utiliser la commande `nohup java -jar /root/app.jar &>/dev/null &` sur l'environnement cible.

NOTE: Afin de charger les credentials précédement créés, il vous faut utiliser `ssh-agent`. Voir https://jenkins.io/doc/pipeline/steps/ssh-agent/

Dans cet exemple, on est sur un déploiement HYPER basique (et pas très très propre :-)). L'objectif est juste de vous montrer les fonctionnalités de Jenkins Pipeline et la "glue" qui permet de passer une étape à l'autre de votre pipeline de livraison.
Pour aller plus loin dans la mise en place du Continuous Delivery, on devrait aborder des problèmatiques spécifiques à chaque techno et ce n'est pas le but de ce workshop centré sur Jenkins Pipeline.

Lancer votre pipeline, vous devriez voir apparaitre l'application PetClinic au bout de quelques secondes sur le port 8080.

=== Création d'une step `deploy`

1. En réutilisant les steps utilisés pour le déploiement sur l'environnement de staging, créer une step `deploy` dans votre library partagée.
Cette step devra utiliser les steps précédemment utilisés. Le but étant d'éviter la duplication des étapes entre le stage de `staging` et celui de `deploy` afin de déployer exactement de la même manière sur les deux environnements cibles.

2. Utiliser ensuite cette méthode pour déployer les binaires de la même manière durant les stages `staging` et `deploy` et vérifier le bon fonctionnement.

3. Modifier votre application PetClinic pour la mise à jour de votre application s'effectue correctement. Par exemple, ajouter un titre dans le fichier HTML `src/main/resources/templates/welcome.html` puis commiter et pusher vos modifications directement sur la branche master.

Vous devriez voir apparaitre vos modifications sur l'environnement de staging, puis sur la prod après avoir approuver l'input.

=== Heuuu, mais elle est ou la baleine ??

Pour ceux qui ont la tremblotte, un tout peu de Docker quand même :-)

Utiliser Docker pour builder l'application au niveau de l'étape `build & unit tests`.
Pour cela, changer le type d'agent en `docker` : vous pouvez utiliser l'image docker `cloudbees/java-build-tools` qui contient tout le nécessaire pour builder votre projet.
